version: '3.7'
services:
  app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "4000:4000"